<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class cube extends \ccxt\Exchange {
    public function public_get_ir_v0_markets($params = array()) {
        return $this->request('ir/v0/markets', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_test($params = array()) {
        return $this->request('test', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetIrV0Markets($params = array()) {
        return $this->request('ir/v0/markets', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetTest($params = array()) {
        return $this->request('test', 'public', 'GET', $params, null, null, array());
    }
}
